image: archlinux
packages:
  - rust
  - scdoc
sources:
  - https://git.sr.ht/~house/ledr
tasks:
  - man: |
      cd ledr
      scdoc < doc/ledr.1.scd > ledr.1
  - format: |
      cd ledr
      cargo fmt --check
  - lint: |
      cd ledr
      cargo clippy
  - build: |
      cd ledr
      cargo build
  - test: |
      cd ledr
      cargo test -- --test-threads=1
